name = "Hensel"
uuid = "eb7cc2b0-7ff9-430e-bfeb-f4d4bef3a6f1"
authors = ["Anatoly Rodionov <anatoly.ya.rodionov@gmail.com>"]
version = "0.1.0"

[deps]
Mahler = "56a8b06d-7817-4acb-864a-ea13953557b9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
